import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ReduxProvider } from "./redux/ReduxProvider";
import ProvidersWrapper from "./ProvidersWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ProvidersWrapper>
            <main className="bg-[#1F1E1C]">
              <Header />
              {children}
              <Footer />
            </main>
          </ProvidersWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
