"use client";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useSelector } from "react-redux";
import { checkLoadingSelector } from "./redux/selector";
import CircularProgress from "@mui/material/CircularProgress";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProvidersWrapper({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLoading = useSelector(checkLoadingSelector);

  // if (isLoading) {
  //   // Render a loading screen...
  //   return <div>Loading...</div>;
  // }

  console.log(isLoading);

  return (
    <SessionProvider>
      <ToastContainer />
      {isLoading && (
        <div className="w-screen h-screen bg-black text-white flex justify-center items-center">
          <CircularProgress className="text-4xl" />
        </div>
      )}
      {children}
    </SessionProvider>
  );
}
